language: go

go:
  - 1.18.1

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox
  
install:
  - # skip

script:
  - gox -os="linux darwin" -arch="amd64" -verbose ./...
  - ls -lrt
  
notifications:
  email: false
